# Generated by Django 5.1.2 on 2024-10-31 16:40

import airplanes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airplane',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='airplane',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=airplanes.models.airplane_image_file_path),
        ),
    ]
